#define TABLECRAWL_NONE 0
#define TABLECRAWL_ATTEMPTING 1
#define TABLECRAWL_PENDING 2
#define TABLECRAWL_UNDER 3

#define TABLE_CRAWL_UNDER_LAYER_OFFSET 0.1
#define TABLE_CRAWL_FULLSCREEN_CATEGORY "table_crawl_view"
